config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は半角英数字混合で設定してください'

  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_many :messages

  validates :nickname, presence: true
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    return unless @message.save

    ActionCable.server.broadcast 'message_channel', content: @message.content, user: @message.user.nickname,
                                                    time: @message.created_at.strftime('%Y/%m/%d %H:%M:%S')
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      current_user.user_rooms.create(room_id: @room.id)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Giver</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="room-title">
    <%= @room.name %>
  </div>
  <% if user_signed_in? %>
  <div class="room-exit">
    <%= link_to "ルーム削除", room_path(@room), method: :delete %>
  </div>
  <% end %>
</div>

<div class="messages" id="messages">
  <%= render partial: "message", collection: @messages %>
</div>

<% if user_signed_in? %>
  <%= form_with model: [@room, @message], class: "form", local: false do |f| %>
    <div class="form-input">
      <%= f.text_field :content, class: "form-message", placeholder: "メッセージを入力" %>
    </div>
    <%= f.submit "送信", class: "form-submit" %>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.nickname %>
    </div>
    <div class="message-date">
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %>
    </div>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="create-room">
    <% if user_signed_in? %>
      <%= link_to "ルーム作成", new_room_path %>
    <% end %>
  </div>
</div>

<div class="rooms">
  <% if user_signed_in? %>
    <% current_user.rooms.each do |room| %>
      <div class="room">
        <div class="room-name">
          <%= link_to room.name, room_messages_path(room) %>
        </div>
      </div>
    <% end %>
    <% Room.where(id: UserRoom.where.not(user_id: current_user.id).pluck(:id)).each do |room| %>
      <div class="room">
        <div class="room-name">
          <%= link_to room.name, room_messages_path(room) %>
        </div>
      </div>
    <% end %>
  <% else %>
    <% Room.all.each do |room| %>
      <div class="room">
        <div class="room-name">
          <%= link_to room.name, room_messages_path(room) %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/messages/index.html.erb
<%= render "shared/header" %>

<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/index.html.erb
<%= render "shared/header" %>

<div class="wrapper">
  <div class="side-bar">
    <%= render "messages/side_bar" %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/rooms/new.html.erb
<%= render "shared/second_header" %>

<%= form_with model: @room, class: 'form-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      ルーム作成
    </h1>
  </div>
  
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ルーム名</label>
    </div>
    <%= f.text_field :name, class:"input-default", placeholder:"ルーム名を入力してください", autofocus: true %>
  </div>
  <div class='submit-btn'>
    <%= f.submit "ルーム作成", class:"submit-btn-green" %>
  </div>
</div>
<% end %>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class='footer'>
  <div class="footer-logo">
    <%= link_to image_tag("logo.png", class:"giver-icon"), "/" %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class="header-logo">
    <%= link_to image_tag("logo.png", class:"giver-icon"), "/" %>
  </div>
  <div class='nav'>
    <ul class='right-header'>
      <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, edit_user_path(current_user), class: "user-nickname" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second_header.html.erb
<header class='second-page-header'>
  <div class="second-haeder-logo">
    <%= link_to image_tag("logo.png", class:"giver-icon"), "/" %>
  </div>
</header>

app/views/users/edit.html.erb
<%= render "shared/second_header" %>

<%= form_with model: current_user, class: "form-main", local: true do |f|%>
<div class="form-wrap">
  <div class="form-header">
    <h2 class="form-header-text">
      アカウント編集
    </h2>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">ニックネーム</label>
    </div>
    <%= f.text_field :nickname, class:"input-default", autofocus: true, placeholder:"例）席郎" %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">メールアドレス</label>
    </div>
    <%= f.email_field :email, class:"input-default", placeholder:"PC・携帯どちらでも可" %>
  </div>
  <div class="submit-btn">
    <%= f.submit "アカウント更新", class:"submit-btn-green" %>
  </div>
</div>
<% end %>

<%= render "shared/footer" %>